name: Generate ASCII Artwork

on:
   push
    
jobs:
     ascii_job:
        runs-on: unbuntu-latest
        steps:
        - name: Checkout Repo
          uses: actions/checout@v4

        - name: List Repo Files
          run: ls -ltra

        - name: Executing Shell Script
          run: ./ascii-script.sh 

#|

#chmod +x ascii-srcipt.sh
        #   - name: Install Cowsay Program
        #   run: sudo apt-get install cowsay -y

        # - name: Execute Cowsay CMD
        #   run: cowsay -f dragon "Run for cover, I an a DRAGON...RAWR" >> dragon.txt

        # - name: Test File Exists
        #   run: grep -i "dragon" dradon.txt

        # - name: Read File
        #   run: cat dragon.txt

        # - name: List Repo Files
        #   run: ls -ltra


